### ISSUE TITLE
Error in WSL

### ISSUE THREAD

**Issue by farzadmf** [ChrisPenner/copy-pasta#2]
Hello,

I've tried installing your plugin in WSL (Windows Subsystem for Linux), and when I do `copy ...`, it gives me the following error:
```
copy:20: copy_pasta_folder: parameter not set
```

Just wondering if there's a way to fix this because I really like the idea of your plugin

**Comment by ChrisPenner** [comment]
This would be really easy to fix I think, it's because I default to a unix-like filepath for the temporary directory: https://github.com/ChrisPenner/copy-pasta/blob/master/copy-pasta.plugin.zsh#L5

Try copying down the script, changing that line to a valid windows temp directory and see if it works. If it does, I can probably check the OS and pick an appropriate filepath based on that. (Or feel free to make a PR 😄 )

**Comment by farzadmf** [comment]
Thank you for your answer, I'm not currently on my Windows machine, but I'll try your fix when I get back to it.

Although I'm a bit skeptic because WSL has its own file system, which is unix-like, so I think the directory `/tmp/copy-pasta` _should_ be valid, but I'll give it a shot anyways :slightly_smiling_face:

**Comment by ChrisPenner** [comment]
It's also possible that simply the `/tmp/` directory is missing, so check for that, alternatively you can try simply deleting `local` from the script, it's possible the system bash version is too old;

If you still have problems try adding `set -x` and `set -e` at the top of the script to see why and where it fails 😄

**Comment by farzadmf** [comment]
Hey @ChrisPenner , so I tested it and seems like removing `local` does the trick 🙂 

But the thing is `bash` doesn't seem to be an old version:
```
bash --version

GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ChrisPenner** [comment]
Ah, I see the issue. The `local` keyword must be used in a function in bash, whereas in zsh it's acceptable elsewhere. I've pushed a new version to master which should remedy this 👍

**Comment by farzadmf** [comment]
That's great @ChrisPenner , thank you for the fix; it would take a while for me to be able to test on my Windows machine, but it should be fine.

So, I'm going to close this, and re-open if the issue is still there (I doubt that would be the case)
